---
title: "Abbreviated Curriculum Vitae"
output: 
  distill::distill_article:
    toc: true
---

# Current Roles

**Quantitative Research Methods in Education PhD Student**

* Organization: University of Oregon
* Start Date: Fall 2020
* Current Graduate Employee Position — Methodologist & Data Scientist. A Study in Equity: Oregon's 9th Grade Transition. Institute of Education Sciences [IES] $881,756 Grant Award number R305S210005

**Statistical Analyst & Data Science Consultant**

* Northwest Data Science (Start Date February 2022) 
* Choose Kindness Foundation (Start Date February 2022)
* Behavioral Research & Teaching (Start Date March 2022)

**Data Science Mentor at RStudio**

* Organization: RStudio Inc.
* Employment Dates: November 2021 — July 2022

# Statistical Software & Package Development 

## Developer & Maintainer

`{gardenr}`: An R Package for Working with Model-Based Recursive Partitioning.
k-fold cross-validation of the multilevel extension of model-based recursive partitioning (i.e., general linear mixed-effects regression trees)

* [Package Website](https://chhr1s.github.io/gardenr/)
* [Git Repository](https://github.com/Chhr1s/gardenr)

## Maintainer

These three packages were developed by Daniel Anderson, PhD; I documented and extended their functionality, and I currently maintain these. Their function is for internal use at BRT. They pull from the Oregon Extended Assessment's database (`{orextdb}`), then process the data to be analyzed (`{dbprocess}`), before analyzing the data with Item Response Theory Models (`{exirt}`).

* [`{orextdb}` Git Repository](https://github.com/UO-BRT/orextdb)
* [`{dbprocess}` Git Repository](https://github.com/UO-BRT/dbprocess)
* [`{exirt}` Git Repository & Package Tutorial](https://github.com/UO-BRT/exirt)

# Education

Doctoral Student: [Quantitative Research Methods in Education](https://education.uoregon.edu/qrme)\n
Department of Education Methodology, Policy, & Leadership\n
College of Education\n
University of Oregon\n

* Advanced to Candidacy Spring 2022
* Fall 2020 - Present
* GPA (to date): 4.13/4.00

Master of Science: [Prevention Science](https://education.uoregon.edu/prevsci/graduate/ms)\n
Department of Counseling Psychology & Human Services\n
College of Education\n
University of Oregon\n

* Fall 2018 - Spring 2020
* GPA: 4.14/4.00 

Bachelor of Arts: [Neuroscience](https://www.hamilton.edu/academics/departments/Home?dept=Neuroscience)\n
Hamilton College\n

* Fall 2011 - Spring 2015
* GPA: 3.61/4.00 

# Manuscripts

## Published:

First Authorship:

[**Loan, C. M.**, Khurana, A., Wright, J., & Romer, D. (2021). Selection versus socialization effects of peer norms on adolescent cigarette use. Tobacco use insights, 14](https://journals.sagepub.com/doi/pdf/10.1177/1179173X211066005)

[Loan, C. M., Rowley, B., Tindal, S., & Tindal, G. (2022). Oregon Extended Assessment Technical Documentation. Behavioral Research and Teaching](https://orext-techreport22.netlify.app/)

Other Authorship (Chronologically):

[Khurana, A., **Loan, C. M.**, Romer, D. (2022). Predicting Cigarette Use Initiation and Dependence in Adolescence Using an Affect-Driven Exploration Model. Frontiers Psychology.](https://www.frontiersin.org/articles/10.3389/fpsyg.2022.887021/full)

[Van Ryzin, M. J., Roseth, C. J., Low, S., & **Loan, C. M.** (2022). Reciprocated Friendship as a Mediator of the Effects of Cooperative Learning on Peer Victimization in Middle School. Journal of School Violence, 1-12.](https://www.tandfonline.com/doi/abs/10.1080/15388220.2022.2098502)

[Clark M., **Loan, C. M.**, Kjellstrand J. (2022) Predictors of Parent-Child Contact During a Parent’s Incarceration. Corrections.](https://www.tandfonline.com/doi/abs/10.1080/23774657.2022.2052381)

[Parr, N. J., **Loan, C. M.**, & Tanner-Smith, E. E. (2021). Using Machine Learning to Identify and Investigate Moderators of Alcohol Use Intervention Effects in Meta-Analyses. Alcohol and Alcoholism.](https://doi.org/10.1093/alcalc/agab036)

[Tanner-Smith, E. E., Nichols, L. M., **Loan, C. M.**, Finch, A. J., & Moberg, D. P. (2020). Recovery High School Attendance Effects on Student Delinquency and Substance Use: the Moderating Role of Social Problem Solving Styles. Prevention Science, 21(8), 1104-1113.](https://doi.org/10.1007/s11121-020-01161-z)


Under Review: 

Kjellstrand, J., Clark, M. Manan, I., & Loan, C.M. (R&R APRIL 2022) Social Support During Incarceration: Predictors of External Social Support for Incarcerated Individuals. American Journal of Criminal Justice.

## Unpublished Documents / Works in Progress:

Loan, C. M., Zvoch, K., & Guha, A. (IN PREP). Using Machine Learning to Identify Inequity in Exclusionary Punishments: An Exploratory Analysis of Historical Data from Schools in Georgia.

Loan, C.M., Tanner-Smith, E. E., & Anderson, D. J. (IN PREP). Exploratory Identification of Meta-Analytic Moderators of Alcohol Use Intervention Effects with General Linear Mixed-Effects Model Regression Trees.

Loan, C. M., Clark, B. M., Delgado-Riley, R. (2022). Latent Transition Analysis of Multidimensional Well-Being Measures of Undergraduates: Assessing a Quasi Experimental Design. Office of Assessment and Research, Division of Student Life, University of Oregon.

Loan, C. M., & Clark, B. A. M. (2020). Wellbeing of International Undergraduates during Initial Months of the COVID-19 Pandemic. Office of Assessment and Research, Division of Student Life, University of Oregon.

Loan, C. M. (2019). Evaluation of 3rd Millennium as a Universal Alcohol and Cannabis Prevention Program at the University of Oregon. Office of Dean of Students, University of Oregon. 

Loan, C. M. (2019). MS Thesis: A Developmental, Behavioral Economics Explanation of Adolescence Cigarette Use & Tobacco Use Disorder Symptom. 

# Selected Poster Presentations: 

Zvoch, K., Scalise, K., Loan, C. M., & Farley, D. (2021, September). Student success teams and Oregon’s 9th grade transition: An in the pipeline investigation of the 9th grade on-track to graduation rate. Poster accepted for presentation at the Annual Meeting of the Society for Research in Educational Effectiveness, Washington, DC.

Loan, C. M., Graham, M.C., Zorilla, E. M., Villanueva, I., Husman, J., & Zvoch, K. (2021, August 12-14). Application of generalized mixed-effect regression trees with multi-modal data [Poster]. APA2021, Remote. https://convention.apa.org/

Marchetti, M., Loan, C. M., Cronce, J. M. (November 2019). An Investigation of Cannabis–related Consequences and Their Predictors Among College Students. Association of Cognitive and Behavioral Therapy (Addictive Behavior Sig), Atlanta, GA.

Loan, C. M. & Khurana, A. (2019). Role of Subjective Affect and Risk Perceptions in Predicting 	Initiation of Adolescent Substance Use. University of Oregon 2019 Graduate Research Forum, Eugene, OR.


# Fun Publications

[Loan, C. &  Williamson, A. (2019, August 25). Do Ratings Take a Dive in Estonia? Retrieved](https://udisc.com/blog/post/do-ratings-take-a-dive-in-estonia)

# Work Experience

## Assessment & Research 
* Assessment & Research Extern | UO Office of Assessment & Research | 2019-Present
* Graduate Research Assistant | Prevention Science Institute (Khurana & DeGarmo Lab) | 2019-2020
* Substance Abuse Prevention Extern | UO Office of Dean of Students | 2019
* Graduate Research Assistant | Prevention Science Institute (Tanner-Smith Lab) | 2019

## Teaching & Course Development

* Course Developer: EDLD 312—Effective Leadership Decision Making | UO College of Education | 2020-Present 
* Teaching Assistant | EDUC 642: Mutliple Regression | UO College of Education | 2020
* Medical College Admissions Test (MCAT) Teacher | Kaplan @ Oregon State University | 2018-2019 (Summers)
* High School Science Teacher | Christ School (Asheville, NC) | 2015-2017

## Administrative

* Data Science Graduate Employee | UO College of Education | 2020-Present 




